account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout, logout_then_login, password_change, password_change_done, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from .forms import AuthForm
from . import views

urlpatterns = [
    # login url
    #url(r'^login/$', views.user_login, name='login'),

    # logged-in urls
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^edit/$', views.edit, name='edit'),
    # register urls
    url(r'^register/$', views.register, name='register'),

    # login/logout urls
    url(r'^login/$', login, {'authentication_form': AuthForm}, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),

    # change password urls
    url(r'^password-change/$', password_change, name='password_change'),
    url(r'^password-change/done/$', password_change_done, name='password_change_done'),

    # reset password urls
    url(r'^password_reset/$', views.password_reset, name="password_reset"),
    url(r'^password-reset/done/$', password_reset_done, name="password_reset_done"),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^password-reset/complete/$', password_reset_complete, name="password_reset_complete"),

]

blog/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPostFeed

urlpatterns = [
    # post views
    url(r'^$', views.home, name='home'),
    url(r'^posts/$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^category/(?P<category>[-\w]+)/$', views.post_list, name='post_list_by_category'),
    url(r'^feed/$', LatestPostFeed(), name='post_feed'),
]

newsportal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    # admin login and urls
    url(r'^admin/', include(admin.site.urls)),
    # user and admin login urls
    url(r'^account/', include('account.urls')),
    # blog urls
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # sitemap url
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # ckeditor urls
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # images share - demo
    url(r'^images/', include('images.urls', namespace='images')),
    # social authentication urls
    url(r'^social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=False, null=False, default='/male3-512.png')

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .models import Profile


class AuthForm(AuthenticationForm):
    username = forms.CharField(label='Username or Email', strip=True, max_length=254, widget=forms.TextInput(attrs={
        'autofocus': '',
        'class': 'form-control'
    }))

    password = forms.CharField(label='Password', strip=False, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        #'placeholder': 'Password'
    }))


class PasswdChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', strip=False, widget=forms.PasswordInput(attrs={
        'autofocus': '',
        'class': 'form-control'
    }))

    password = forms.CharField(label='New password', strip=False, widget=forms.PasswordInput(attrs={
        'autofocus': '',
        'class': 'form-control'
    }))

    password2 = forms.CharField(label='Confirm new password', strip=False, widget=forms.PasswordInput(attrs={
        'autofocus': '',
        'class': 'form-control'
    }))


class UserRegistrationForm(forms.ModelForm):
    first_name = forms.CharField(label='First name', strip=True, max_length=80, required=True)
    email = forms.CharField(label='Email', widget=forms.EmailInput, required=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'test'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name", widget=forms.TextInput(attrs={
        'class': 'float-right'
    }), required=True)
    last_name = forms.CharField(label="Last Name", required=False, widget=forms.TextInput(attrs={
        'class': 'float-right'
    }))
    email = forms.CharField(label="Email", widget=forms.TextInput(attrs={
        'class': 'float-right'
    }), required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    date_of_birth = forms.DateField(label='Date of birth', required=False, widget=forms.DateInput(attrs={
        'class': 'float-right'
    }))

    photo = forms.ImageField(label='Change a photo', required=False, widget=forms.FileInput(attrs={
        'class': 'float-right'
    }))

    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.views import password_reset as django_password_reset
from django.core.exceptions import ObjectDoesNotExist

from .models import Profile
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm


@login_required
def welcome(request):
    try:
        Profile.objects.get(user=request.user)
    except ObjectDoesNotExist:
        Profile.objects.create(user=request.user)

    return HttpResponseRedirect(reverse('blog:post_list'))


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html', {'section': 'dashboard'})


@login_required
def edit(request):
    try:
        user_profile = Profile.objects.get(user=request.user)
    except ObjectDoesNotExist:
        user_profile = Profile.objects.create(user=request.user)

    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
            return HttpResponseRedirect(reverse('edit'))
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    #user_profile = Profile.objects.get(user=request.user)

    return HttpResponse(render(request, 'account/edit.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'user_profile': user_profile
    }))


def password_reset(request, *args, **kwargs):
    email_template_name = 'registration/password_reset_email.html'
    return django_password_reset(request, html_email_template_name=email_template_name, *args, **kwargs)


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # create user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # save the user object
            new_user.save()

            # create the user profile
            profile = Profile.objects.create(user=new_user)

            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()

    return render(request, 'account/register.html', {'user_form': user_form})

account/templates/base.html
{% load blog_tags %}
{% load staticfiles %}
{% load sass_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% sass_src 'css/blog.scss' %}" rel="stylesheet">
    {% block css %}{% endblock css %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
    {% include 'navbar.html' %}
        <!--<span class="logo"><a href="{% url 'blog:post_list' %}">The Watchers</a></span>-->
        <!--{% if request.user.is_authenticated %}-->
        <!--<ul class="menu">-->
            <!--<li {% if section == "dashboard" %} class="selected" {% endif %}>-->
                <!--<a href="{% url 'dashboard' %}">Dashboard</a>-->
            <!--</li>-->
            <!--<li {% if section == "images" %} class="selected" {% endif %}>-->
                <!--<a href="#">Images</a>-->
            <!--</li>-->
            <!--<li {% if section == "people" %} class="selected" {% endif %}>-->
                <!--<a href="#">People</a>-->
            <!--</li>-->
        <!--</ul>-->
        <!--{% endif %}-->

        <!--<span class="user">-->
            <!--{% if request.user.is_authenticated %}-->
                <!--Hello {{ request.user.first_name }},-->
                <!--<a href="{% url 'logout' %}">Logout</a>-->
            <!--{% else %}-->
                <!--<a href="{% url 'login' %}">Log-in</a>-->
            <!--{% endif %}-->
        <!--</span>-->
    <div class="container">
        <div class="row">
            <section id="content" class="col-xl-12">
                {% block content %}{% endblock content %}
            </section>
            <div class="">
                <!--{% show_latest_posts 5 %}-->
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/tether.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    {% block js %}{% endblock js %}
    <script>
        {% block script %}{% endblock script %}
    </script>
</body>
</html>

account/templates/base_old.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
</head>
<body>
    <div id="header">
        <span class="logo">The Watchers</span>
        {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "dashboard" %} class="selected" {% endif %}>
                <a href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li {% if section == "images" %} class="selected" {% endif %}>
                <a href="#">Images</a>
            </li>
            <li {% if section == "people" %} class="selected" {% endif %}>
                <a href="#">People</a>
            </li>
        </ul>
        {% endif %}

        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name }},
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close" onclick="closeMessage(this)">X</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div id="content">
        {% block content %}{% endblock content %}
    </div>
    <script type="text/javascript">
        var closeMessage = function(e) {
            var target = $(e);
            target.parent().slideUp();
        }
    </script>
</body>
</html>

account/templates/navbar.html
{% load blog_tags %}
<header>
    <nav class="nav fixed-top">
        <ul class="nav col-xl-2 justify-content-center">
            <li class="nav-item">
                <a class="navbar-brand logo" href="{% url 'blog:home' %}">Vault 13</a>
            </li>
        </ul>
        <ul class="nav col-xl-8 justify-content-center">
        {% show_categories %}
        </ul>
        <ul class="nav col-xl-2 justify-content-end">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown user">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hello {{ request.user.first_name }}</a>
                <div class="dropdown-menu user">
                    {% if request.user.is_superuser %}
                    <a class="dropdown-item" href="{% url 'admin:login' %}">Admin</a>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'dashboard' %}">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item user">
                <a class="nav-link login" href="{% url 'login' %}">LOGIN</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</header>