blog/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPostFeed

urlpatterns = [
    # post views
    url(r'^$', views.home, name='home'),
    url(r'^posts/$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^category/(?P<category>[-\w]+)/$', views.post_list, name='post_list_by_category'),
    url(r'^feed/$', LatestPostFeed(), name='post_feed'),
]

newsportal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    # admin login and urls
    url(r'^admin/', include(admin.site.urls)),
    # user and admin login urls
    url(r'^account/', include('account.urls')),
    # blog urls
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # sitemap url
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # ckeditor urls
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # images share - demo
    url(r'^images/', include('images.urls', namespace='images')),
    # social authentication urls
    url(r'^social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class PostCategory(models.Model):

    name = models.CharField(max_length=30, null=False, blank=False, unique=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     self.name = self.name.capitalize()
    #     super(PostCategory, self).save(*args, **kwargs)


class PostSubcategory(models.Model):

    name = models.CharField(max_length=40, unique=True, blank=False, null=False)
    category = models.ForeignKey(PostCategory, related_name='category', null=False, blank=False)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     self.name = self.name.capitalize()
    #     super(PostSubcategory, self).save(*args, **kwargs)


class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_posts', null=False, blank=True)
    category = models.ForeignKey(PostCategory, related_name='post_category', null=False, blank=False)
    subcategory = models.ForeignKey(PostSubcategory, related_name='post_subcategory', null=False, blank=False)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    image = models.ImageField(upload_to='uploads/post/%Y/%m/%d', blank=False, null=False)
    summary = models.TextField(default='summary')
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
    featured = models.BooleanField(default=0)

    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug
        ])

    def save(self, *args, **kwargs):
        self.category = self.subcategory.category
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):

    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {0} on {1}'.format(self.name, self.post)

blog/forms.py
from django import forms
from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from blog.models import Post, Comment, PostCategory
from blog.forms import EmailPostForm, CommentPostForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def home(request):
    featured_posts = Post.published.all().filter(featured=1)[:5]
    categories = PostCategory.objects.all()

    latest_posts = Post.published.all()[:8]
    last_featured_post = featured_posts[0]
    featured_posts = featured_posts[1:]

    return render(request, 'blog/home.html', {
        'last_featured_post': last_featured_post,
        'featured_posts': featured_posts,
        'latest_posts': latest_posts,
        'categories': categories
    })


def post_list(request, tag_slug=None, category=None):
    # get all published posts
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    if category:
        category_name = get_object_or_404(PostCategory, name=category)
        object_list = object_list.filter(category=category_name)

    # pagination for all posts (default 3 posts per page)
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    # try get requested page
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, return first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range, return last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False 

    # if request method is POST, try validate form
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    # if method is GET, create empty form
    elif request.method == 'GET':
        form = EmailPostForm()
    
    return render(request, 'blog/post/share.html', { 'post': post, 'form': form, 'sent': sent })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    
    # list of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentPostForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentPostForm()
        new_comment = False

    return render(request, 'blog/post/post_detail.html', {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'new_comment': new_comment,
        'similar_posts': similar_posts
    })

blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
{% load sass_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% sass_src 'css/blog.scss' %}" rel="stylesheet">
    {% block css %}{% endblock css %}
</head>
<body>
    {% include 'navbar.html' %}
    {% if not request.user.is_authenticated %}
    {% endif %}
    <div class="container">
        <div class="row top-ad">
            <div class="col-sm-12">
                <img src="/media/ads/top-ad_970x90.jpeg">
            </div>
        </div>
        <div class="row">
            <section class="message col-sm-12">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                        <a href="#" class="close" onclick="closeMessage(this)">X</a>
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </section>
        </div>
        {% block content %}{% endblock content %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/tether.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    {% block js %}{% endblock js %}
    <script>
        $(document).ready(function(){
            {% block domready %}
            {% endblock %}
        });
    </script>
    <script type="text/javascript">
        var closeMessage = function(e) {
            var target = $(e);
            target.parent().slideUp();
        }
    </script>
</body>
</html>

blog/templates/blog/base_old.html
{% load blog_tags %}
{% load staticfiles %}

<!DOCTYPE html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <script src="{% static 'js/modernizer.js' %}"></script>
        <link href="{% static 'css/normalize.css' %}" rel="stylesheet">
        <!-- Font Awesome -->
        <script src="https://use.fontawesome.com/489521b7c1.js"></script>
        <!-- Formstone -->
        <link href="{% static 'formstone/css/grid.css' %}" rel="stylesheet">
        <link href="{% static 'formstone/css/navigation.css' %}" rel="stylesheet">
        <link href="{% static 'formstone/css/tabs.css' %}" rel="stylesheet">
        <link href="{% static 'formstone/css/tooltip.css' %}" rel="stylesheet">
        <!-- Custom Blog style -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body class="fs-grid fs-grid-fluid">

    <!-- Navigation -->
    <!-- Menu button -->
    <div class="nav_content">
        <button type="button" class="nav_handle">Menu</button>
    </div>
    <!-- Menu -->
    <nav class="fs-navigation" data-navigation-handle=".nav_handle" data-navigation-content=".nav_content">
        <div class="fs-row">
            <div class="fs-cell-centered fs-xs-3 fs-sm-3 fs-md-6 fs-lg-12 fs-xl-10">
                <a href="#"><i class="fa fa-home" aria-hidden="true"></i></a>
                <a href="#">Two</a>
                <a href="#">Three</a>
                <a href="#">Four</a>
                <a href="#">Five is very long menu link that is unusually long</a>
                <div class="dropdown">
                    <a href="javascript:void(0)" class="dropbtn" onclick="myFunction()">Dropdown</a>
                    <div class="dropdown-content" id="myDropdown">
                        <a href="#">Link 1</a>
                        <a href="#">Link 2</a>
                        <a href="#">Link 3</a>
                    </div>
                </div>
                <a href="#">Test</a>
            </div>
        </div>
    </nav>

    <!-- Central content -->
    <div class="fs-grid fs-grid-fluid example">
        <div class="fs-row">
            <div class="fs-cell-centered fs-xs-3 fs-sm-3 fs-md-6 fs-lg-12 fs-xl-10">

                <!-- Main content -->
                <div class="fs-cell fs-xs-3 fs-sm-3 fs-md-4 fs-lg-8 content">
                    {% block content %}{% endblock content %}
                </div>
                <!-- Sidebar -->
                <div class="fs-cell fs-xs-3 fs-sm-3 fs-md-2 fs-lg-4 sidebar">
                    {% show_latest_posts 5 %}
                </div>

            </div>
        </div>
        <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
    </div>

    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <!-- Formstone -->
    <script src="{% static 'formstone/js/core.js' %}"></script>
    <script src="{% static 'formstone/js/mediaquery.js' %}"></script>
    <script src="{% static 'formstone/js/swap.js' %}"></script>
    <script src="{% static 'formstone/js/navigation.js' %}"></script>
    <script src="{% static 'formstone/js/tabs.js' %}"></script>
    <script src="{% static 'formstone/js/tooltip.js' %}"></script>

    <!-- Formstone script -->
    <script>
        $(".fs-navigation").navigation({
            type: "overlay",
            gravity: "left"
        });

        $(".swap").swap();

        $(".tab").tabs({
            mobileMaxWidth: 500
        });

        $(".tooltip").tooltip({
            direction: "bottom",
            match: true,
            follow: true
        });
    </script>

    <!-- Custom script for dropdown menu -->
    <script>
        /* When the user clicks on the button, 
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function(e) {
            if (!e.target.matches('.dropbtn')) {

                var dropdowns = document.getElementsByClassName("dropdown-content");
                for (var d = 0; d < dropdowns.length; d++) {
                    var openDropdown = dropdowns[d];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Vault 13{% endblock title %}

{% block content %}
    <div class="home">
        <div class="row">
            <div class="col-sm-8 featured no-horizontal-padding">
                <a href="{{ last_featured_post.get_absolute_url }}">
                    <img src="{{ last_featured_post.image.url }}">
                    <div class="overlay">
                        <h2>{{ last_featured_post.title }}</h2>
                        <p>{{ last_featured_post.summary }}</p>
                    </div>
                </a>
            </div>
            {% show_latest_posts 8 %}
        </div>
        <div class="row featured-sm no-horizontal-padding">
            {% for post in featured_posts %}
            <div class="col-sm-3 featured-post no-horizontal-padding">
                <img src="{{ post.image.url }}">
                <div class="overlay">
                    <h2>{{ post.title }}</h2>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row categories">
            <div class="col-sm-4">
                <div class="card">
                    <img class="card-img-top" src="{{ featured_posts.image.url }}">
                    <div class="card-block">
                        <h4 class="card-title">{{ featured_posts.title }}</h4>
                        <p class="card-text">{{ featured_posts.summary }}</p>
                        <a href="{{ featured_posts.get_absolute_url }}" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <img class="card-img-top" src="https://unsplash.it/200/300/?random">
                    <div class="card-block">
                        <h4 class="card-title">Title</h4>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <img class="card-img-top" src="https://unsplash.it/200/300/?random">
                    <div class="card-block">
                        <h4 class="card-title">Title</h4>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/navbar_categories.html
<ul class="nav col-xl-8 justify-content-center">
    {% for category in categories %}
    <li class="nav-item">
        <a class="nav-link menu" href="{% url 'blog:post_list_by_category' category.name %}">{{  category.name }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/sidebar.html
<h2>Sidebar</h2>
<p>This is my first blog</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam bibendum nisi id erat hendrerit congue mattis a libero. Etiam consequat dapibus arcu, eu placerat massa posuere in. Aenean faucibus urna justo, vitae pharetra nunc fringilla non. In eleifend felis at ultrices sollicitudin. Phasellus et auctor sem, rhoncus eleifend mauris. Integer id tellus id lectus scelerisque sollicitudin. Nunc metus sem, volutpat in efficitur a, efficitur id lectus. Mauris hendrerit eget sem nec fringilla. Sed at orci cursus, bibendum augue et, pellentesque quam. Pellentesque sollicitudin tortor tellus, ut faucibus mauris commodo eu. Mauris volutpat auctor purus, vulputate molestie metus mattis ac. Donec egestas luctus tortor.</p>

<div role="tablist">
    <nav>
        <a href="#tab-one" class="tab" data-tabs-group="tab-group">One</a>
        <a href="#tab-two" class="tab" data-tabs-group="tab-group" data-tabs-active="true">Two</a>
        <a href="#tab-three" class="tab" data-tabs-group="tab-group">Three</a>
    </nav>
    <div id="tab-one">
        <h3>Title of The Tab One</h3>
        <p>Phasellus et auctor sem, rhoncus eleifend mauris. Integer id tellus id lectus scelerisque sollicitudin. Nunc metus sem, volutpat in efficitur a, efficitur id lectus. Mauris hendrerit eget sem nec fringilla. Sed at orci cursus, bibendum augue et, pellentesque
        quam. Pellentesque sollicitudin tortor tellus, ut faucibus mauris commodo eu</p>
        <h3>Title of The Tab One</h3>
        <p>Nunc metus sem, volutpat in efficitur a, efficitur id lectus. Mauris hendrerit eget sem nec fringilla. Sed at orci cursus, bibendum augue et, pellentesque
        quam. Pellentesque sollicitudin tortor tellus, ut faucibus mauris commodo eu. Pellentesque sollicitudin tortor tellus, ut faucibus mauris commodo eu. Mauris volutpat auctor purus, vulputate molestie metus mattis ac. Pellentesque sollicitudin tortor tellus, ut faucibus mauris commodo eu. Mauris volutpat auctor purus.</p>
    </div>
    <div id="tab-two">
        <a href="page.html" class="tooltip" data-title="Welcome to New York"><img src="http://lorempixel.com/output/city-q-g-500-300-3.jpg" alt=""></a>
    </div>
    <div id="tab-three">
        <h3>Title of The Tab Three</h3>
        <p> Etiam consequat dapibus arcu, eu placerat massa posuere in. Aenean faucibus urna justo, vitae pharetra nunc fringilla non. In eleifend felis at ultrices sollicitudin. Phasellus et auctor sem, rhoncus eleifend mauris. Integer id tellus id lectus scelerisque sollicitudin. Nunc metus sem, volutpat in efficitur a, efficitur id lectus. Mauris hendrerit eget sem nec fringilla. Sed at orci cursus, bibendum augue et, pellentesque quam. Pellentesque sollicitudin tortor tellus, ut faucibus mauris commodo eu. Mauris volutpat auctor purus, vulputate molestie metus mattis ac.</p>
    </div>
</div>