blog/urls.py
from django.conf.urls import url

from . import views
from .feeds import LatestPostFeed

urlpatterns = [
    # post views
    url(r'^$', views.home, name='home'),
    url(r'^posts/$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^category/(?P<category>[-\w]+)/$', views.post_list, name='post_list_by_category'),
    url(r'^feed/$', LatestPostFeed(), name='post_feed'),
]

newsportal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    # admin login and urls
    url(r'^admin/', include(admin.site.urls)),
    # user and admin login urls
    url(r'^account/', include('account.urls')),
    # blog urls
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # sitemap url
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # ckeditor urls
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # images share - demo
    url(r'^images/', include('images.urls', namespace='images')),
    # social authentication urls
    url(r'^social-auth/', include('social.apps.django_app.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class PostCategory(models.Model):

    name = models.CharField(max_length=30, null=False, blank=False, unique=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     self.name = self.name.capitalize()
    #     super(PostCategory, self).save(*args, **kwargs)


class PostSubcategory(models.Model):

    name = models.CharField(max_length=40, unique=True, blank=False, null=False)
    category = models.ForeignKey(PostCategory, related_name='category', null=False, blank=False)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     self.name = self.name.capitalize()
    #     super(PostSubcategory, self).save(*args, **kwargs)


class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_posts', null=False, blank=True)
    category = models.ForeignKey(PostCategory, related_name='post_category', null=False, blank=False)
    subcategory = models.ForeignKey(PostSubcategory, related_name='post_subcategory', null=False, blank=False)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    image = models.ImageField(upload_to='uploads/post/%Y/%m/%d', blank=False, null=False)
    summary = models.TextField(default='summary')
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')
    featured = models.BooleanField(default=0)

    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug
        ])

    def save(self, *args, **kwargs):
        self.category = self.subcategory.category
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):

    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {0} on {1}'.format(self.name, self.post)

blog/forms.py
from django import forms
from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from blog.models import Post, Comment, PostCategory
from blog.forms import EmailPostForm, CommentPostForm


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def home(request):
    featured_posts = Post.published.all().filter(featured=1)[:5]
    categories = PostCategory.objects.all()

    latest_posts = Post.published.all()[:8]
    last_featured_post = featured_posts[0]
    featured_posts = featured_posts[1:]

    return render(request, 'blog/home.html', {
        'last_featured_post': last_featured_post,
        'featured_posts': featured_posts,
        'latest_posts': latest_posts,
        'categories': categories
    })


def post_list(request, tag_slug=None, category=None):
    # get all published posts
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    if category:
        category_name = get_object_or_404(PostCategory, name=category)
        object_list = object_list.filter(category=category_name)

    # pagination for all posts (default 3 posts per page)
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    # try get requested page
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, return first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range, return last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page, 'tag': tag})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False 

    # if request method is POST, try validate form
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    # if method is GET, create empty form
    elif request.method == 'GET':
        form = EmailPostForm()
    
    return render(request, 'blog/post/share.html', { 'post': post, 'form': form, 'sent': sent })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    
    # list of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentPostForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentPostForm()
        new_comment = False

    return render(request, 'blog/post/post_detail.html', {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'new_comment': new_comment,
        'similar_posts': similar_posts
    })

blog/templates/blog/post/detail_old.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}

<div class="post-content-full">
    <h2>{{ post.title }}</h2>
    <span class="date">
        <i class="fa fa-calendar" aria-hidden="true"></i> {{ post.publish }} <i class="fa fa-user-circle-o" aria-hidden="true"></i> {{ post.author }}
    </span>
    <div>
        <img src="http://lorempixel.com/output/nature-q-g-1024-600-3.jpg" alt="image">
        {{ post.body|markdown }}
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </div>
</div>


<h2>Similar posts</h2>
{% for post in similar_posts %}
<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
{% empty %}
There is no similar posts yet
{% endfor %}

<div class="comment-form">
    {% if new_comment %}
    <h2>Your comment has been added.</h2>
    {% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
    {% endif %}
</div>

{% with comments.count as total_comments %}
<h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
{% endwith %}

<div class="comments">
    {% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
    {% endfor %}
</div>
{% endblock content %}
{% include "blog/sidebar.html" %}

blog/templates/blog/post/latest_posts.html
<div class="col-sm-4 sidebar">
    <h2>Latest News</h2>
    <div class="latest-list">
        {% for post in latest_posts %}
        <a class="btn btn-link btn-block align-top" href="{{ post.get_absolute_url }}">{{ post.title }}<span>3 days ago</span></a>
        {%  endfor %}
    </div>
</div>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock title %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.summary|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include "blog/pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/post_detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
    <div class="post-content">
        <div class="row">
            <div class="col-sm-12 post-title">
                <h1>{{ post.title }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 post">
                <div class="col-sm-12 post-image">
                    <img src="{{ post.image.url }}">
                </div>
                <div class="col-sm-12 body-top-ad">
                    <img src="/media/ads/ad_728x90.jpg">
                </div>
                <div class="col-sm-12 post-body">
                    <p>{{ post.body|markdown }}</p>
                </div>
                <div class="col-sm-12 body-bottom-ad">
                    <img src="/media/ads/ad_728x90.jpg">
                </div>
            </div>
            <div class="col-sm-4 sidebar">
                {% show_latest_posts 9 %}
                <div class="sidebar-top-ad">
                    <img src="/media/ads/sidebar_ad_300x600.gif">
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock title %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ cd.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by Email</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send E-mail">
        </form>
    {% endif %}
{% endblock content %}